# resonates configuration file
# Place in ~/.config/resonates/resonates.toml (Linux/macOS) or %APPDATA%/resonates/resonates.toml (Windows)

[general]
max_size = 2048
max_file_size = 100_000_000
max_lines = 0
max_files = 20000
recursive = false
force = false

[files]
file_types = ["rs", "js", "jsx", "ts", "tsx"]
exclude = ["node_modules", "target", "dist", "build", ".git", "*.lock", "package-lock.json"]

[similarity]
mode = "token"  # "none", "token", "embedding"
threshold = 0.86
top_k = 300
min_tokens = 6
cross_file_only = true
include_snippets = false

# Token-based similarity
band_bits = 8

# Pre-filtering pipeline
enable_pre_filtering = true
size_ratio_max = 5.0      # Skip if size difference > 5x
pre_token_threshold = 0.1 # Liberal token filter before embedding
ast_type_matching = true  # Only compare compatible AST node types

[embedding]
model = "jina-embeddings-v2-base-code"
batch_size = 32
chunk_batch_size = 5000

# ANN parameters
k = 15
ef_construction = 200
ef_search = 96
m = 16
verify_min_jaccard = 0.20

[output]
folder = "./_analysisjsons/"
analysis_file = "/analysis.json"
similarity_file = "similarity.json"
graph_file = "/graph.json"
api_backend_file = "/api_backend.json"
api_frontend_file = "/api_frontend.json"
api_map_file = "/api_map.json"
suspects_file = "/suspects.json"

[progress]
verbosity = "normal"  # "quiet", "normal", "verbose"
show_progress_bars = true
print_similarity_pairs = false
print_limit = 10